# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccgate < Formula
  desc "LLM-powered PermissionRequest hook for coding agents (e.g. Claude Code)"
  homepage "https://github.com/tak848/ccgate"
  version "0.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tak848/ccgate/releases/download/v0.9.1/ccgate-darwin-amd64.tar.gz"
      sha256 "0409ca9ed4fc967659c46f50c817e73fa16f8c6b2b92f6cbd4350496dd6c4c5c"

      define_method(:install) do
        bin.install "ccgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tak848/ccgate/releases/download/v0.9.1/ccgate-darwin-arm64.tar.gz"
      sha256 "46abd11e0e3638b441061f8d9bbeae776a9f9da5fcfd6d1b60ea672e8764ef3b"

      define_method(:install) do
        bin.install "ccgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tak848/ccgate/releases/download/v0.9.1/ccgate-linux-amd64.tar.gz"
      sha256 "1f01f3af89e560df96062881edee921da130b5b502e4e0e4d91332d523fa8ed4"
      define_method(:install) do
        bin.install "ccgate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tak848/ccgate/releases/download/v0.9.1/ccgate-linux-arm64.tar.gz"
      sha256 "033e30e583605f806700b45b0632cf657110e39806a7c40d4c46714ccbdbf809"
      define_method(:install) do
        bin.install "ccgate"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ccgate --version")
  end
end
