# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccgate < Formula
  desc "LLM-powered PermissionRequest hook for coding agents (e.g. Claude Code)"
  homepage "https://github.com/tak848/ccgate"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tak848/ccgate/releases/download/v0.9.0/ccgate-darwin-amd64.tar.gz"
      sha256 "65ccd105336d40a4152b77e3c3df914a9b7547c29c6bc1fc7700694a95e7f72a"

      define_method(:install) do
        bin.install "ccgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tak848/ccgate/releases/download/v0.9.0/ccgate-darwin-arm64.tar.gz"
      sha256 "ec5a71440a5fcfffedb1a5eed068466fa86767b5f4678a548d5f4313e99c1a46"

      define_method(:install) do
        bin.install "ccgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tak848/ccgate/releases/download/v0.9.0/ccgate-linux-amd64.tar.gz"
      sha256 "65cc604f3030f6ebb171d7f2b36bfb88de71ccc622b7eaf34f0b81e8d8bd21c0"
      define_method(:install) do
        bin.install "ccgate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tak848/ccgate/releases/download/v0.9.0/ccgate-linux-arm64.tar.gz"
      sha256 "b627b9e64cf1d7abb9ffd09fba9d8b588bb0ef3894b0449a4e160365a3aae70b"
      define_method(:install) do
        bin.install "ccgate"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ccgate --version")
  end
end
