# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccgate < Formula
  desc "LLM-powered PermissionRequest hook for coding agents (e.g. Claude Code)"
  homepage "https://github.com/tak848/ccgate"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tak848/ccgate/releases/download/v0.11.0/ccgate-darwin-amd64.tar.gz"
      sha256 "817ee6a55b9cfdeffaef9794865bfbd2eaa41fc40a6e25a388f2d5fe1b88bf86"

      define_method(:install) do
        bin.install "ccgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tak848/ccgate/releases/download/v0.11.0/ccgate-darwin-arm64.tar.gz"
      sha256 "c358b82db962c396fb909eb9cae0a090e0209337d8093771c5eb6e5b37215cb1"

      define_method(:install) do
        bin.install "ccgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tak848/ccgate/releases/download/v0.11.0/ccgate-linux-amd64.tar.gz"
      sha256 "892b1ff67949715c42ac6a2e713a3da2f68015fab8cfacc8ff50954fa81f0f39"
      define_method(:install) do
        bin.install "ccgate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tak848/ccgate/releases/download/v0.11.0/ccgate-linux-arm64.tar.gz"
      sha256 "02bfbe0ea851059977a2f46da32fe06b314d1babdb96d0bdde0c316e95c176d4"
      define_method(:install) do
        bin.install "ccgate"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ccgate --version")
  end
end
